config/routes.rb
Rails.application.routes.draw do
  root to: 'games#index'

  devise_for :players

  resources :games
  
  resources :player_participation, only: [:create, :destroy], param: :game
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  enum status: { pending: 0, in_progress: 1, finished: 2, archived: 3 }
  
  belongs_to :owner, class_name: "Player"
  has_many :player_participations, dependent: :destroy
  has_many :players, through: :player_participations
  
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :owned_games, class_name: "Game"
  has_many :player_participations
  has_many :games, through: :player_participations
  
  def to_s
    email
  end
  
end

app/models/player_participation.rb
class PlayerParticipation < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

app/controllers/api/concerns/response.rb
module API::Concerns::Response
    def json_response(object, status = :ok)
        render json: object, status: status
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_player!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_player!, only: [:index]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show

  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit

  end

  # POST /games
  def create
    @game = Game.new(status: 0, owner: current_player)

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:status, :owner_id)
    end
end

app/controllers/player_participation_controller.rb
class PlayerParticipationController < ApplicationController
    # POST /player_participations
    def create
        return if player_participation_params[:game].blank? || player_participation_params[:player].blank?
        
        game = Game.find(player_participation_params[:game])
        player = Player.find(player_participation_params[:player])
        
        return if game.blank? || player.blank?
        
        if game.players.include?(player)
            redirect_to game, notice: 'Welcome back!'
        else
            game.players << player
            redirect_to game, notice: 'Successfully joined the game.'
        end
    end

    def destroy
        game = Game.find(player_participation_params[:game])

        participation = game.player_participations.find_by(player: current_player)
        
        participation.destroy
        
        redirect_to game, notice: 'Successfully left the game.'
    end
    
    
    private
    
    def player_participation_params
      params.permit(:game, :player, :_method, :authenticity_token)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/player_participation_helper.rb
module PlayerParticipationHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Start Game' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="page_content_heading">
  <h1>Games</h1><%= link_to 'New Game', new_game_path, class: 'btn btn-outline-secondary' if current_player %>  
</div>

<table class="table table-dark table-striped">
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <div class="card text-white bg-dark mb-3">
          <div class="card-body">
            <h5 class="card-title" style="display:inline">Game Name...</h5>
            <div class="" style="display:inline; float:right">
              <%= link_to 'Show', game_path(game), class: 'btn btn-outline-secondary', style:'display:inline' if current_player%>
              <% if current_player && game.owner == current_player %>
                <%= link_to 'Edit', edit_game_path(game), class: 'btn btn-outline-secondary', style:'display:inline' %>
                <%= link_to 'Destroy', game_path(game), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-secondary', style:'display:inline' %>
              <% else %>
                &nbsp;
              <% end %>
            </div>
            <p>
              <div class="container">
                <div class="row">
                  <div class="col-sm-6">
                    <p>Owner: <b><%= game.owner %></b></p>
                    <p>Status: <b><%= game.status %></b></p>
                  </div>
                  <div class="col-sm-6">
                    <div class="card text-white bg-dark mb-3">
                      <div class="card-body">
                        <h5 class="card-title">Participants:</h5>
                          <% game.players.each do |player| %>
                            <p><%= player %></p>
                          <% end %>
                          <% if game.players.exclude?(current_player) %>
                            <p>
                              <%= link_to 'Join', player_participation_index_path(game: game, player: current_player), method: :post, class: 'btn btn-outline-primary' if current_player%>
                            </p>
                          <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </p>
          </div>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= render 'shared/chat', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <p>
        <strong>Status:</strong>
        <%= @game.status %>
      </p>
      <p>
        <strong>Owner:</strong>
        <%= @game.owner %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <strong>
        Participants:
      </strong>
      <% unless @game.players.include?(current_player) %>
        <%= link_to 'Join', player_participation_index_path(game: @game, player: current_player), method: :post, class: 'btn btn-outline-primary', style:'display:inline' if current_player %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-11">
      <p>
        <% @game.players.each do |player| %>
          <p>
            <%= player %>
            <% if player == current_player %>
            <%= link_to 'Leave Game', player_participation_path(game: @game, player: player), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger', style:'display:inline' %>
            <% end %>
          </p>
        <% end %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= link_to 'Edit', edit_game_path(@game) %> |
      <%= link_to 'Back', games_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>RadioSilence</title>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container" id="main_container">
      <%= yield %>  
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_chat.html.erb
<%= content_tag(:div, '', id: 'chat_window') %>

app/views/shared/_footer.html.erb
<footer class="page-footer bg-dark" id="footer">
  <div class="container-fluid text-center text-md-left">
    &copy; The BGG 2019
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
  <a class="navbar-brand" href="/">Radio Silence...</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% class_list = controller.controller_name == "games"? "nav-link active" : "nav-link" %>
        <%= link_to 'Games', games_path, class: class_list %>
      </li>
    </ul>
    <div class="my-2 my-lg-0">
      <% if player_signed_in? %>
        <%= current_player.email %>
        <%= link_to 'Sign out', destroy_player_session_path, method: :delete, class: "btn btn-outline-secondary" %>
      <% else %>
        <%= link_to 'Sign up', new_player_registration_path, class: "btn btn-outline-secondary" %>
        <%= link_to 'Sign in', new_player_session_path, class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>